#version: "2"
#services:
#  app:
#    build: ./src_vue
#    links:
#      - db
#    ports:
#      - "80:80"
#  db:
#    image: mariadb:10.4.6
#    volumes:
#      - ./db/dump.sql:/docker-entrypoint-initdb.d/dump.sql
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: scot
#      MYSQL_USER: user
#      MYSQL_PASSWORD: password

#//user:password@db/scot

version: "2.1"
networks:
  scot-net:
services:
  app:
    build: ./src_vue
    volumes:
      - .:/src_vue
    links:
      - db
    ports:
      - "10017:80"
    networks:
      scot-net:
    #depends_on:
    #  - db_setup

  #db_setup:
  #  build: ./src_build_database
  #  volumes:
  #    - ./db/gbooks_datahub/:/make_db/data
  #  depends_on:
  #    db:
  #      condition: service_healthy
  #  networks:
  #    scot-net:


  db:
    image: mariadb:10.4.6
    volumes:
      # database
      - ${PWD}/db/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - ${PWD}/db/dev_data:/var/lib/mysql
     # - ${PWD}/db/moreWordsforAlex:/var/lib/mysql-files

      # "database" : "mysql://user:password@db/scot" / local: "mysql://inga@0.0.0.0/scot"(config.json)
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: scot
      MYSQL_USER: user
      MYSQL_PASSWORD: password

    #healthcheck:
    #      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-ppassword", "-uuser"]
    #      interval: 120s
    #      timeout: 20s
    #      retries: 40

    networks:
      scot-net:
